---
version: 0.2
phases:
  install:
    commands:
      - echo $PATH
      - wget https://github.com/gohugoio/hugo/releases/download/v0.57.2/hugo_0.57.2_Linux-32bit.tar.gz
      - tar -vxf hugo_0.52_Linux-64bit.tar.gz
      - ./hugo version
      - aws --version
  pre_build:
    commands:
      - ./hugo -v --baseURL "" --buildDrafts --destination public/
  build:
    commands:
      - aws s3 sync --no-progress --delete public/ s3://$S3_WEBSITE_BUCKET
  post_build:
    commands:
      - ls -Fl public/
