---
version: 0.2
phases:
  install:
    commands:
      - echo $PATH
      - wget --no-verbose https://github.com/gohugoio/hugo/releases/download/v0.62.2/hugo_0.62.2_Linux-64bit.tar.gz -O hugo.tgz
      - tar -vxf hugo.tgz
      - ./hugo version
      - aws --version
  pre_build:
    commands:
      - make hugo PATH="$PWD:$PATH"
  build:
    commands:
      - make sync S3_WEBSITE_BUCKET=$S3_WEBSITE_BUCKET
  post_build:
    commands:
      - ls -Fl public/
