---
version: 0.2
phases:
  install:
    commands:
      - echo $PATH
      - wget https://github.com/gohugoio/hugo/releases/download/v0.39/hugo_0.39_Linux-64bit.tar.gz
      - tar -vxf hugo_0.39_Linux-64bit.tar.gz
      - ./hugo version
      - aws --version
  pre_build:
    commands:
      - ./hugo -v --buildDrafts --destination public/ --baseURL $WEBSITE_URL
  build:
    commands:
      - aws s3 sync --delete --acl 'public-read' 'public/' 's3://$S3_WEBSITE_BUCKET'
  post_build:
    commands:
      - ls -Fl public/
