AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Providing Lambda-backed Custom Resources for
  Amazon Certificate Manager

Resources:
  RequestCertificateFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code: ../lambda/
      Description: String
      Handler: request_certificate.handler
      MemorySize: 128
      Role: !GetAtt CertificateProviderLambdaRole.Arn
      Runtime: python3.8
      Timeout: 5

  GetAcmCnameFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code: ../lambda/
      Description: String
      Handler: get_acm_cname.handler
      MemorySize: 128
      Role: !GetAtt CertificateProviderLambdaRole.Arn
      Runtime: python3.8
      Timeout: 5

  UpdateCnameFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code: ../lambda/
      Description: String
      Handler: update_cname.handler
      MemorySize: 128
      Role: !GetAtt CertificateProviderLambdaRole.Arn
      Runtime: python3.8
      Timeout: 5

  RequestCertificate:
    Type: "Custom::RequestCertificate"
    Properties:
      ServiceToken: !GetAtt RequestCertificateFunction.Arn
      DomainName: random10.felipe1982.com

  GetAcmCname:
    Type: "Custom::GetAcmCname"
    Properties:
      ServiceToken: !GetAtt GetAcmCnameFunction.Arn
      CertificateArn: !GetAtt RequestCertificate.Arn
      DomainName: random10.felipe1982.com

  # UpdateCname:
  #   Type: "Custom::UpdateCname"
  #   Properties:
  #     ServiceToken: !GetAtt UpdateCnameFunction.Arn
  #     HostedZoneId: Z1JYG3XEZZ05O1
  #     Name: !GetAtt GetAcmCname.Name
  #     Type: !GetAtt GetAcmCname.Type
  #     Value: !GetAtt GetAcmCname.Value

  CertificateProviderLambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: Request ACM Certificates
      ManagedPolicyArns:
        - arn:aws:iam::638088845137:policy/write-cloudwatch-logs
      Path: /service-role/
      Policies:
        - PolicyName: RequestAcmCertificates
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'acm:DescribeCertificate'
                  - 'acm:GetCertificate'
                  - 'acm:ListCertificates'
                  - 'acm:RequestCertificate'
                Resource: '*'
        - PolicyName: UpdateResourceRecordSets
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'route53:ChangeResourceRecordSets'
                  - 'route53:ListResourceRecordSets'
                  - 'route53:GetChange'
                Resource: '*'
