AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Providing Lambda-backed Custom Resources for
  Amazon Certificate Manager

Resources:
  PrintCname:
    Type: "Custom::PrintCname"
    Properties:
      ServiceToken: !GetAtt CertificateProvider.Arn
      DomainName: boto3.felipe1982.com
      CertificateArn: 'arn:aws:acm:us-east-1:638088845137:certificate/def5f55f-13b6-49dd-9d85-477d19f275ef'
  CertificateProvider:
    Type: "AWS::Lambda::Function"
    Properties:
      Code: ../lambda/
      Description: String
      Handler: get_certificate_dns_validation_cname.handler
      MemorySize: 128
      Role: !GetAtt CertificateProviderLambdaRole.Arn
      Runtime: python3.8
      Timeout: 5
  CertificateProviderLambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: Request ACM Certificates
      ManagedPolicyArns:
        - arn:aws:iam::638088845137:policy/write-cloudwatch-logs
      Path: /service-role/
      Policies:
        - PolicyName: RequestAcmCertificates
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'acm:DescribeCertificate'
                  - 'acm:GetCertificate'
                  - 'acm:ListCertificates'
                  - 'acm:RequestCertificate'
                Resource: '*'

Outputs:
  Name:
    Value: !GetAtt PrintCname.Name
  Type:
    Value: !GetAtt PrintCname.Type
  Value:
    Value: !GetAtt PrintCname.Value
